### ISSUE TITLE
Clicking on RSS feed link fails (Opera)

### ISSUE THREAD

**Issue by iambacon** [remy/remysharp.com#26]
Clicking the RSS link results in the following error

```
TypeError: Failed to construct 'URL': Invalid URL
```

**Comment by remy** [comment]
Are you clicking the link in the footer (or somewhere else)?

I get it loading this url: https://remysharp.com/feed.xml

And then I see the XML - what do you see?

**Comment by iambacon** [comment]
This is what I see in the browser

![image](https://cloud.githubusercontent.com/assets/2139123/21006499/138ca868-bd31-11e6-98bf-33e348c46445.png)

**Comment by remy** [comment]
hmm. Could you test in an incognito/private window? I'll do the same as
soon as I'm back in front of my machine (also, thank you for reporting,
keen to fix as I've had an RSS feed for 10 years, and I don't want it
breaking now!)

**Comment by iambacon** [comment]
This is what I get in a private window.

![image](https://cloud.githubusercontent.com/assets/2139123/21007007/38e4a906-bd33-11e6-9318-a297c05cb677.png)

No error but blank. No errors in dev tools either.

**Comment by remy** [comment]
Okay thanks. I can see you're using Opera, and though similar (in ways) to
chrome, I'll test using Opera too.

I'll post back here with a fix (I hope!).

Thanks again.

**Comment by remy** [comment]
Cracked it. Updated version should be live in the next few minutes.

Turns out to be a bug in the rendering engine for RSS in Opera (url below), tl;dr: Opera's RSS parser doesn't like relative urls in feeds (which there was _one_ due to a brittle regexp in my code).

http://www.opera.com/blogs/desktop/2016/10/86-percent-faster-opera-41-for-computers/#comment-2972415887
